services:
  - type: web
    name: getRanking
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=$PORT
    packages:
      - unixodbc-dev
